name: Panadero-Core
version: '${project.version}'
main: plugin.panaderocore.Panadero_Core
api-version: '1.20'

commands:
  afk:
    description: afk
  panadero:
    description: panadero
    permission: op